<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>appicon.ico</ApplicationIcon>
    <RootNamespace>XForensics.App</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XForensics.Core\XForensics.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*" />
    <Resource Include="appicon.ico" />
    <Content Include="appicon.ico" />
  </ItemGroup>
</Project>
